core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', IndexPage.as_view(), name='index_page'),
    
    path('profile', ProfileDetail.as_view(), name='profile_detail'),
    path('profile/edit', EditProfile.as_view(), name='edit_profile'),
    
]

daily_task/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('tasks.urls', namespace='tasks')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import *

app_name = "tasks"

urlpatterns = [
    path('tasks/', DailyTaskList.as_view(), name='dailytask_list'),
    path('tasks/historical', HistoricalDailyTaskList.as_view(), name='historical_dailytask_list'),
    path('tasks/create', CreateDailyTask.as_view(), name='create_dalitask'),
    path('tasks/<int:pk>', get_dailytask_detail, name='dailytask_detail'),
    path('tasks/<int:pk>/complete', complete_task, name='complete_task'),
    
]

core/models.py
from django.db import models
from .model_states import *


def get_path_profile_image(instance, filename):
    return 'profile_images/{0}/{1}'.format(instance.user.username, filename)

class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDER, null=True, blank=True)
    other_gender = models.CharField(max_length=100, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=150, null=True, blank=True)
    phone_number = models.CharField(max_length=25, null=True, blank=True)
    profile_image = models.ImageField(upload_to=get_path_profile_image, verbose_name="Profile Image", default="default.png")
    
    class Meta:
        verbose_name = 'User Profile'
        verbose_name_plural = 'Users Profiles'
        
    def __str__(self):
        return 'User Profile from %s %s'%(self.user.first_name, self.user.last_name)

tasks/models.py
from django.db import models

class DailyTask(models.Model):
    name            = models.CharField(max_length=170)
    description     = models.TextField(null=True, blank=True)
    completed       = models.BooleanField(default=False)
    completed_date  = models.DateTimeField(null=True, blank=True)
    limit_date      = models.DateField(null=True, blank=True)
    created_date    = models.DateTimeField(auto_now_add=True)
    user            = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Daily Task'
        verbose_name_plural = 'Daily Tasks'
        
    def __str__(self):
        return 'Daily Tasks from %s'%(self.user)

core/forms.py
from django.forms import ModelForm, Form, TextInput, Select, DateInput, FileInput
from .models import *

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['gender', 'other_gender', 'birth_date', 'location', 'phone_number', 'profile_image']
        
        widgets = {
            'gender': Select(attrs={ 'class': 'form-control' }),
            'other_gender': TextInput(attrs={ 'class': 'form-control' }),
            'location': TextInput(attrs={ 'class': 'form-control' }),
            'phone_number': TextInput(attrs={ 'class': 'form-control' }),
            'profile_image': FileInput(attrs={ 'class': 'form-control', 'accept': 'image/png, image/jpg, image/jpeg' }),
        }

tasks/forms.py
from django import forms
from .models import *

class DailyTaskForm(forms.ModelForm):
    class Meta:
        model = DailyTask
        fields = ['name', 'description', 'limit_date']
        
        widgets = {
            'name': forms.TextInput(attrs={ 'class': 'form-control', 'required': True }),
            'description': forms.Textarea(attrs={ 'class': 'form-control' }),
        }

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import *
from django.contrib.auth.models import User
from .forms import *
from django.urls import reverse

class IndexPage(TemplateView):
    template_name = 'core/index-page.html'
    
@method_decorator(login_required, name='dispatch')
class ProfileDetail(TemplateView):
    template_name = 'accounts/profile-detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"] = UserProfile.objects.get(user=self.request.user)
        return context
    
@method_decorator(login_required, name='dispatch')
class EditProfile(UpdateView):
    model = UserProfile
    template_name = "accounts/edit-profile.html"
    form_class = UserProfileForm
    
    def get_object(self):
        return UserProfile.objects.get(user=self.request.user)
    
    def form_valid(self, form):
        if form.is_valid():
            f = form.save(commit=False)
            user_data = self.request.POST
            first_name = user_data.get('first_name')
            last_name = user_data.get('last_name')
            User.objects.filter(pk=self.request.user.pk).update(first_name=first_name, last_name=last_name)
            f.save()
        
        return super(EditProfile, self).form_valid(form)
    
    def get_success_url(self):
        return reverse('core:profile_detail')
    

tasks/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .forms import *
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.utils import timezone

@method_decorator(login_required, name='dispatch')
class DailyTaskList(ListView):
    model = DailyTask
    template_name = 'daily-tasks/list.html'
    
    def get_queryset(self):
        today = timezone.now().date()
        return DailyTask.objects.filter(user=self.request.user, limit_date__gte=today)
    
@method_decorator(login_required, name='dispatch')
class HistoricalDailyTaskList(ListView):
    model = DailyTask
    template_name = 'daily-tasks/historical_list.html'
    
    def get_queryset(self):
        today = timezone.now().date()
        return DailyTask.objects.filter(user=self.request.user, limit_date__lt=today)
    
    
@method_decorator(login_required, name='dispatch')
class CreateDailyTask(CreateView):
    model = DailyTask
    template_name = 'daily-tasks/create.html'
    form_class = DailyTaskForm
    
    def form_valid(self, form):
        if form.is_valid():
            f = form.save(commit=False)
            f.user = self.request.user
            f.save()
        return super(CreateDailyTask, self).form_valid(form)
    
    def get_success_url(self):
        return reverse('tasks:dailytask_list')
    
@login_required
def complete_task(request, pk):
    today = timezone.now().date()
    try:
        task = DailyTask.objects.get(pk=pk, user=request.user)
        
        if today <= task.limit_date:
            task.completed = True
            task.completed_date = timezone.now()
            task.save()
        else:
            # you can't complete this task
            pass
    except:
        raise Http404()
    
    return redirect('tasks:dailytask_list')

@login_required
def get_dailytask_detail(request, pk):
    try:
        task = DailyTask.objects.get(pk=pk, user=request.user)
        
        date = task.completed_date.date() if task.completed_date else None
        
        data = {
            'name': task.name,
            'description': task.description,
            'completed': task.completed,
            'completed_date': date,
            'limit_date': task.limit_date,
        }
    except:
        data = {
            'error': 'error'
        }
    
    
    return JsonResponse(data)

core/templates/accounts/edit-profile.html
{% extends "base/index.html" %}

{% block page_title %}Edit Profile{% endblock page_title %}

{% block page_content %}

<div class="container">
    <div class="row justify-content">
        <div class="col-xl-9">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Profile</h6>
                </div>
                <div class="card-body">
                    <form action="" method="post" class="user" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-xl-12 mb-2">
                                <div class="form-group">
                                    <label for="" class="form-label">Profile Image</label>
                                    {{ form.profile_image }}
                                </div>
                            </div>
                            <div class="col-xl-6 mb-2">
                                <label for="" class="form-label">First Name</label>
                                <input type="text" name="first_name" id="id_first_name" class="form-control" value="{{ object.user.first_name }}">
                            </div>
                            <div class="col-xl-6 mb-2">
                                <label for="" class="form-label">Last Name</label>
                                <input type="text" name="last_name" id="id_last_name" class="form-control" value="{{ object.user.last_name }}">
                            </div>
                            <div class="col-xl-6 mb-2">
                                <label for="" class="form-label">Gender</label>
                                {{ form.gender }}
                            </div>
                            <div class="col-xl-6 mb-2" id="other_gender" style="display: none;">
                                <label for="" class="form-label">Other Gender</label>
                                {{ form.other_gender }}
                            </div>
                            <div class="col-xl-6 mb-2">
                                <label for="" class="form-label">Birth Date</label>
                                <input type="date" name="birth_date" id="id_birth_date" class="form-control" value="{{ object.birth_date|date:'Y-m-d' }}">
                            </div>
                            <div class="col-xl-6 mb-2">
                                <label for="" class="form-label">Phone Number</label>
                                {{ form.phone_number }}
                            </div>
                            <div class="col-xl-6 mb-2">
                                <label for="" class="form-label">Location</label>
                                {{ form.location }}
                            </div>
                        </div>
                        <hr>
                        <button class="btn btn-primary btn-block">Save Profile</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    const gender = document.querySelector('#id_gender');

    gender.addEventListener('change', e => {

        if (e.target.value === '3') {
            $('#other_gender').show();
        } else {
            $('#other_gender').hide();
        }
    });

</script>

{% endblock page_content %}

core/templates/accounts/profile-detail.html
{% extends "base/index.html" %}

{% load static %}

{% block page_title %}Profile{% endblock page_title %}

{% block page_content %}

<a href="{% url "core:edit_profile" %}" class="btn btn-primary"><i class="fas fa-edit"></i> Edit Profile</a>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-xl-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Profile Image</h6>
                </div>
                <div class="card-body">
                    <img src="{{ object.profile_image.url }}" alt="" class='mx-auto' style="width: 250px; height: 250px; clip-path: circle(50%); display: block; margin-left: auto; margin-right: auto;">
                    {% comment %} <img src="{% static "img/undraw_profile.svg" %}" alt=""> {% endcomment %}
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Profile Info</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-12 mb-2">
                            <div class="form-group">
                                <label for="" class="form-label">Username</label>
                                <input type="text" class="form-control" readonly value="{{ user.username }}">
                            </div>
                        </div>
                        <div class="col-xl-6 mb-2">
                            <div class="form-group">
                                <label for="" class="form-label">First Name</label>
                                <input type="text" class="form-control" readonly value="{{ user.first_name }}">
                            </div>
                        </div>
                        <div class="col-xl-6 mb-2">
                            <div class="form-group">
                                <label for="" class="form-label">Last Name</label>
                                <input type="text" class="form-control" readonly value="{{ user.last_name }}">
                            </div>
                        </div>
                        <div class="col-xl-12 mb-2">
                            <div class="form-group">
                                <label for="" class="form-label">Email Address</label>
                                <input type="text" class="form-control" readonly value="{{ user.email }}">
                            </div>
                        </div>
                        <div class="col-xl-6 mb-2">
                            <label for="" class="form-label">Gender</label>
                            <input type="text" class="form-control" readonly value="{% if object.gender == '3' %}{% else %}{{ object.get_gender_display|default_if_none:"" }}{% endif %}">
                        </div>
                        <div class="col-xl-6 mb-2">
                            <label for="" class="form-label">Birth Date</label>
                            <input type="text" class="form-control" readonly value="{{ object.birth_date|date:'SHORT_DATE_FORMAT' }}">
                        </div>
                        <div class="col-xl-6 mb-2">
                            <label for="" class="form-label">Phone Number</label>
                            <input type="text" class="form-control" readonly value="{{ object.phone_number|default_if_none:"" }}">
                        </div>
                        <div class="col-xl-6 mb-2">
                            <label for="" class="form-label">Location</label>
                            <input type="text" class="form-control" readonly value="{{ object.location|default_if_none:"" }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock page_content %}

core/templates/base/footer/footer.html
{% load static %}

<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; DailyTask 2023</span>
        </div>
    </div>
</footer>

core/templates/base/menu/sidebar.html
{% load static %}

<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">DailyTasks</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    {% if not user.is_anonymous %}

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="/">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Tasks
    </div>
    
    <li class="nav-item">
        <a class="nav-link" href="{% url "tasks:create_dalitask" %}">
            <i class="fas fa-fw fa-plus"></i>
            <span>Create Task</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "tasks:dailytask_list" %}">
            <i class="fas fa-fw fa-tasks"></i>
            <span>Tasks List</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url "tasks:historical_dailytask_list" %}" class="nav-link">
            <i class="fas fa-fw fa-tasks"></i>
            <span>Historical Tasks List</span>
        </a>
    </li>

    {% comment %} 

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="utilities-color.html">Colors</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
                <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li> {% endcomment %}

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
    {% endif %}
</ul>

tasks/templates/daily-tasks/create.html
{% extends "base/index.html" %}

{% load static %}

{% block page_title %}Create Task{% endblock page_title %}

{% block page_content %}

<h1 class="h3 mb-4 text-gray-800">Create Task</h1>

<div class="row">
    <div class="col-xl-8 mx-auto">
        <div class="card border-left-primary">
            <form action="{% url "tasks:create_dalitask" %}" method="post">
                {% csrf_token %}
                <div class="card-body">
                    <div class="form-group">
                        <label for="" class="form-label">Name Task</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label for="" class="form-label">Limit Date</label>
                        <input type="date" name="limit_date" id="id_limit_date" class="form-control" value="{% now "Y-m-d" %}" required>
                    </div>
                    <div class="form-group">
                        <label for="" class="form-label">Description</label>
                        {{ form.description }}
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary">Create Task</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock page_content %}

tasks/templates/daily-tasks/historical_list.html
{% extends "base/index.html" %}

{% load static %}
{% load task_tags %}

{% block page_title %}Task List{% endblock page_title %}

{% block page_content %}

<h1 class="h3 mb-4 text-gray-800">Task List</h1>

<div class="row">
    {% for x in object_list %}
    <div class="col-lg-6">
        {% validate_state_task x.pk as state_task %}
        <div class="card mb-4 py-3 border-bottom-{{ state_task }}">
            <div class="card-body d-flex justify-content-between">
                <div class="h4">{{ x.name }}</div>
                <div>
                    <span class="fa-stack fa-2x">
                        <a href="{% url "tasks:dailytask_detail" x.pk %}">
                            <i class="fas fa-search fa-stack-1x view-detail" data-bs-toggle="tooltip" data-bs-placement="top" title="Detail"></i>
                        </a>
                    </span>
                    {% if x.completed %}
                    <span class="fa-stack fa-2x">
                        <a style="cursor:pointer">
                            <i class="far fa-check-square fa-stack-1x" data-bs-toggle="tooltip" data-bs-placement="top" title="Task Completed" style="color: #1cc88a;"></i>
                        </a>
                    </span>
                    {% elif not x.completed and state_task == 'danger' %}
                    <span class="fa-stack fa-2x">
                        <a style="cursor: pointer;">
                            <i class="fas fa-times fa-stack-1x" data-bs-toggle="tooltip" data-bs-placement="top" title="Out of time to complete the task" style="color: #e74a3b"></i>
                        </a>
                    </span>
                    {% elif not x.completed %}
                    <span class="fa-stack fa-2x">
                        <a href="{% url "tasks:complete_task" x.pk %}">
                            <i class="far fa-square fa-stack-1x complete-task" data-bs-toggle="tooltip" data-bs-placement="top" title="Complete Task"></i>
                        </a>
                    </span>
                    {% endif %}
                    
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock page_content %}

{% block script %}

<script>
    $('.complete-task').click( async e => {
        e.preventDefault();

        const { isConfirmed } = await Swal.fire({
            title: 'Complete the task',
            text: 'Are you sure about completed the task?',
            icon: 'question',
            showCancelButton: true,
            confirmButtonText: "yes, i'm complete the task",
            cancelButtonText: 'No, go back',
        });

        if( isConfirmed ) {
            const url = e.target.parentElement.href;
            window.location = url;
        }

    } );
</script>

<script>
    $('.view-detail').click( async e => {
        e.preventDefault()
        const url = e.target.parentElement.href;
        const response = await fetch(url, { method: 'GET' });

        if( response.ok ) {
            const data = await response.json();

            const html = document.createElement('div');
            html.classList.add('row');

            html.innerHTML = `
                <div class="col-md-12 mb-2">
                    <label class="form-label">Name</label>
                    <input type="text" class="form-control" value="${data.name}" readonly style="background-color: #FFF;"/>
                </div>
                <div class="col-md-4 mb-2">
                    <label class="form-label">Limit Date</label>
                    <input type="text" class="form-control" value="${data.limit_date }" readonly style="background-color: #FFF;"/>
                </div>
                <div class="col-md-4 mb-2">
                    <label class="form-label">Completed</label>
                    <input type="text" class="form-control" value="${data.completed ? "Yes" : "No" }" readonly style="background-color: #FFF;"/>
                </div>
                <div class="col-md-4 mb-2">
                    <label class="form-label">Completed Date</label>
                    <input type="text" class="form-control" value="${data.completed_date ? data.completed_date : "No completed"}" readonly style="background-color: #FFF;"/>
                </div>
                <div class="col-md-12 mb-2">
                    <label class="form-label">Completed Date</label>
                    <textarea class="form-control" rows="4" cols="50" readonly style="background-color: #FFF; resize: none;">${data.description}</textarea>
                </div>
            `

            Swal.fire({
                title: 'Daily Task Detail',
                html,
                width: '75%',
                showConfirmButton: false,
                showCloseButton: true,
            })
        }

    } )
</script>

{% endblock script %}

tasks/templates/daily-tasks/list.html
{% extends "base/index.html" %}

{% load static %}
{% load task_tags %}

{% block page_title %}Task List{% endblock page_title %}

{% block page_content %}

<h1 class="h3 mb-4 text-gray-800">Task List</h1>

<div class="row">
    {% for x in object_list %}
    <div class="col-lg-6">
        {% validate_state_task x.pk as state_task %}
        <div class="card mb-4 py-3 border-bottom-{{ state_task }}">
            <div class="card-body d-flex justify-content-between">
                <div class="h4">{{ x.name }}</div>
                <div>
                    <span class="fa-stack fa-2x">
                        <a href="{% url "tasks:dailytask_detail" x.pk %}">
                            <i class="fas fa-search fa-stack-1x view-detail" data-bs-toggle="tooltip" data-bs-placement="top" title="Detail"></i>
                        </a>
                    </span>
                    {% if x.completed %}
                    <span class="fa-stack fa-2x">
                        <a style="cursor:pointer">
                            <i class="far fa-check-square fa-stack-1x" data-bs-toggle="tooltip" data-bs-placement="top" title="Task Completed" style="color: #1cc88a;"></i>
                        </a>
                    </span>
                    {% elif not x.completed and state_task == 'danger' %}
                    <span class="fa-stack fa-2x">
                        <a style="cursor: pointer;">
                            <i class="fas fa-times fa-stack-1x" data-bs-toggle="tooltip" data-bs-placement="top" title="Out of time to complete the task" style="color: #e74a3b"></i>
                        </a>
                    </span>
                    {% elif not x.completed %}
                    <span class="fa-stack fa-2x">
                        <a href="{% url "tasks:complete_task" x.pk %}">
                            <i class="far fa-square fa-stack-1x complete-task" data-bs-toggle="tooltip" data-bs-placement="top" title="Complete Task"></i>
                        </a>
                    </span>
                    {% endif %}
                    
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock page_content %}

{% block script %}

<script>
    $('.complete-task').click( async e => {
        e.preventDefault();

        const { isConfirmed } = await Swal.fire({
            title: 'Complete the task',
            text: 'Are you sure about completed the task?',
            icon: 'question',
            showCancelButton: true,
            confirmButtonText: "yes, i'm complete the task",
            cancelButtonText: 'No, go back',
        });

        if( isConfirmed ) {
            const url = e.target.parentElement.href;
            window.location = url;
        }

    } );
</script>

<script>
    $('.view-detail').click( async e => {
        e.preventDefault()
        const url = e.target.parentElement.href;
        const response = await fetch(url, { method: 'GET' });

        if( response.ok ) {
            const data = await response.json();

            const html = document.createElement('div');
            html.classList.add('row');

            html.innerHTML = `
                <div class="col-md-12 mb-2">
                    <label class="form-label">Name</label>
                    <input type="text" class="form-control" value="${data.name}" readonly style="background-color: #FFF;"/>
                </div>
                <div class="col-md-4 mb-2">
                    <label class="form-label">Limit Date</label>
                    <input type="text" class="form-control" value="${data.limit_date }" readonly style="background-color: #FFF;"/>
                </div>
                <div class="col-md-4 mb-2">
                    <label class="form-label">Completed</label>
                    <input type="text" class="form-control" value="${data.completed ? "Yes" : "No" }" readonly style="background-color: #FFF;"/>
                </div>
                <div class="col-md-4 mb-2">
                    <label class="form-label">Completed Date</label>
                    <input type="text" class="form-control" value="${data.completed_date ? data.completed_date : "No completed"}" readonly style="background-color: #FFF;"/>
                </div>
                <div class="col-md-12 mb-2">
                    <label class="form-label">Completed Date</label>
                    <textarea class="form-control" rows="4" cols="50" readonly style="background-color: #FFF; resize: none;">${data.description}</textarea>
                </div>
            `

            Swal.fire({
                title: 'Daily Task Detail',
                html,
                width: '75%',
                showConfirmButton: false,
                showCloseButton: true,
            })
        }

    } )
</script>

{% endblock script %}